version: "3.7"

services:
  nodejs:
    image: rest-app
    restart: on-failure
    container_name: nodejsserver
    hostname: nodejsserver
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - mongo    
  mongo:
    image: mongo
    container_name: mongo
    volumes:
       - ./data:/data/db
    ports:
       - "27017:27017" 
       
  nginx:
    image:nginx
    copy:
      src: ./default.conf
      dest: /etc/nginx/conf.d/
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80" 
    depends_on:
      - nodejs-app
  
