version: "3.7"

services:
  nodejs:
    image: rest-app
    restart: on-failure
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - mongo
    volumes: 
       db-config:
       db-data:

  mysql:
    image: mysql:8.0
    restart: on-failure
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      
  mongo:
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db